apiVersion: v1
kind: Secret
metadata:
    name: acr-pull-secret
    namespace: socpoc
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ntBKsTqqbhJsZHQOjjkqQzzwwcPUeSvjDLYDMppdU6hNTZETRD6qYa2BqEb1vb61XyJYhHjEIa3+t0kyBmz3+tjQkIaB2FiOEg48Xm1RcXcP97xFtF9NP32x1Sbj9KKo+FiHtPBmr43x2ayDPhTB/TwROuVK4VyflGSs/5lWbYI48cgSX5UXJSXTytX2Asu6zdsz0ITP0EONOewiiI8h+cfIUvZSjOFTsJ8uBXtrrZQkiBDQoO0l+qyeCxm6U6nqzDPG5/v1UMl77eUOz5Ny8qB40SwthTsA0uzfve0afkHxpotIK8NTL5MyHdY8vc8PYKAU5mRnEK2pW7MzdmxKWw7+TdhZuwou0E4b9gbRkyvXunpCP+AFl5PfrAnPUpwkhXrPySK5d1hN8cq4gn2T8v8L+5mQPYi8QbOyVwrdveHoqhmLCclV4gCnNtvZC9fE4c6AKTNdXr4vR3Avn6w=,iv:liekvSCetWTHndQwKMeQ7bxs/GDoII/ZD7fIkwo0Mnw=,tag:RKenINSIuLlS5KgnkvkoDg==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-socintpoc-demo.vault.azure.net
          name: socintpoc
          version: 4515b93353484f89a25c4adb81026f7a
          created_at: "2026-06-16T18:02:06Z"
          enc: fe00nbmTG56W4t2F44PysrvL1s568ST4mHd0aLd-2QP5jbGY4I1kIWpbMAxGg2bB0Ur5toTA3cmDLvU-o5aGezkoh2UGY2bUgkBm1s0WCyxb3qjxbfddI0obUOynJO9KkMYKqSYa9BHcCzUTKZBhhTItOOuNDXfygpaoWHofuuAXR21ji8yyhUzO3tLGoyXyDOVTuyW2eHFCrMUqcgZ0kTr-Lo6VchJnoJAU8_YPdhvZ2n7SQa3b6nEdTj3o9_tlIwcOVKjY2_MGUqqNPr6TVZgP4mZoh3VX_bJ2OuMhL7K5ieGYodWIsXrfTDMjIPkdua9FYoD-TeUkza49ELCivg
    lastmodified: "2026-06-16T18:02:09Z"
    mac: ENC[AES256_GCM,data:wtO4s7nhlNQ2Q+KsJMXVgnTiqotbHJxkYXKFr8Qa/TxlptYwIoSpke8RC+csQInHCHqBQHGMvRK303m5VdJImLoAE2h6a007nTB3i2sepQWjWzSPHHsG1hbCReu/mAaeFK6rHbKrBr5nrPsJG1GDOZl8d2rN1Vw2Jh5Ytqw32N4=,iv:ZyaEACmYRPtJW/KjBYs66GcMVzt3sWHJQUykey6jAJM=,tag:u5Vcr4iBoENtWwDFKjpyFQ==,type:str]
    encrypted_regex: ^(data|stringData|github_token|password|account_key)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: acr-helm-secret
    namespace: socpoc
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:hCQTkcJoO7HLgBWnqQ42HMstWCoj5ynkYMdCcCghJX9XvFODhVvaqBzV3NqRYilsRmBWDqX60cQkM1RWeNVyLSZfvVk5idwV6EdpoW6XXvJePrM5U1NQyHyzovb93R1IhM3KnROoKZ25c8S/IRh8K4rOM56M/c45IWzkT+2ICn/8fMHkVvjPYbq4DtNipxv47vpIGUkRGePsw58S947oSyolCdhzWUW9rMHFsP1WwsM7GcX71KU5AE7rpS4s3em7JDm4V4nRfwsoapnEbQrwO0E0wtAC/+vKXZ4RMuHknyP8ArlvMXOy6bfJdcGxGrHIHxBFouqBWl7cTrnAgCLu2CHH4xA6iRwfU0ChqDey0YAoD066bWSJ068ejyzbSP/rcLnAMl8zr9GylCx0GBDIQon/mvQYGHfN22zvdljcliIVVDak94ZGe9nxm5d0IzIWDUvlnElkJqQ55QdCY6A=,iv:KedYjdDzouWwgYOnkUlKutyuBQn0/6M3UlQ3ms5xdc8=,tag:slnZ1dEQ5e4Jxc5Ol56Z2w==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-socintpoc-demo.vault.azure.net
          name: socintpoc
          version: 4515b93353484f89a25c4adb81026f7a
          created_at: "2026-06-16T18:02:06Z"
          enc: fe00nbmTG56W4t2F44PysrvL1s568ST4mHd0aLd-2QP5jbGY4I1kIWpbMAxGg2bB0Ur5toTA3cmDLvU-o5aGezkoh2UGY2bUgkBm1s0WCyxb3qjxbfddI0obUOynJO9KkMYKqSYa9BHcCzUTKZBhhTItOOuNDXfygpaoWHofuuAXR21ji8yyhUzO3tLGoyXyDOVTuyW2eHFCrMUqcgZ0kTr-Lo6VchJnoJAU8_YPdhvZ2n7SQa3b6nEdTj3o9_tlIwcOVKjY2_MGUqqNPr6TVZgP4mZoh3VX_bJ2OuMhL7K5ieGYodWIsXrfTDMjIPkdua9FYoD-TeUkza49ELCivg
    lastmodified: "2026-06-16T18:02:09Z"
    mac: ENC[AES256_GCM,data:wtO4s7nhlNQ2Q+KsJMXVgnTiqotbHJxkYXKFr8Qa/TxlptYwIoSpke8RC+csQInHCHqBQHGMvRK303m5VdJImLoAE2h6a007nTB3i2sepQWjWzSPHHsG1hbCReu/mAaeFK6rHbKrBr5nrPsJG1GDOZl8d2rN1Vw2Jh5Ytqw32N4=,iv:ZyaEACmYRPtJW/KjBYs66GcMVzt3sWHJQUykey6jAJM=,tag:u5Vcr4iBoENtWwDFKjpyFQ==,type:str]
    encrypted_regex: ^(data|stringData|github_token|password|account_key)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: backend-db-secret
    namespace: socpoc
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:MtAk9F0tFVgMnsRrVSCWHCozIWIdLMhvll9xwzqvVjU=,iv:Wq9pYMwxEgTeh5E/JehW3gxqdJ03R4v3+Ik++Jro1g4=,tag:3Z4/pIb0Y3EMfJYjS/vspw==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-socintpoc-demo.vault.azure.net
          name: socintpoc
          version: 4515b93353484f89a25c4adb81026f7a
          created_at: "2026-06-16T18:02:06Z"
          enc: fe00nbmTG56W4t2F44PysrvL1s568ST4mHd0aLd-2QP5jbGY4I1kIWpbMAxGg2bB0Ur5toTA3cmDLvU-o5aGezkoh2UGY2bUgkBm1s0WCyxb3qjxbfddI0obUOynJO9KkMYKqSYa9BHcCzUTKZBhhTItOOuNDXfygpaoWHofuuAXR21ji8yyhUzO3tLGoyXyDOVTuyW2eHFCrMUqcgZ0kTr-Lo6VchJnoJAU8_YPdhvZ2n7SQa3b6nEdTj3o9_tlIwcOVKjY2_MGUqqNPr6TVZgP4mZoh3VX_bJ2OuMhL7K5ieGYodWIsXrfTDMjIPkdua9FYoD-TeUkza49ELCivg
    lastmodified: "2026-06-16T18:02:09Z"
    mac: ENC[AES256_GCM,data:wtO4s7nhlNQ2Q+KsJMXVgnTiqotbHJxkYXKFr8Qa/TxlptYwIoSpke8RC+csQInHCHqBQHGMvRK303m5VdJImLoAE2h6a007nTB3i2sepQWjWzSPHHsG1hbCReu/mAaeFK6rHbKrBr5nrPsJG1GDOZl8d2rN1Vw2Jh5Ytqw32N4=,iv:ZyaEACmYRPtJW/KjBYs66GcMVzt3sWHJQUykey6jAJM=,tag:u5Vcr4iBoENtWwDFKjpyFQ==,type:str]
    encrypted_regex: ^(data|stringData|github_token|password|account_key)$
    version: 3.12.2
