apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/demo/cluster-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: base-infra
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-staging
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-prod
