apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      containers:
      - env:
        - name: AZURE_AUTH_METHOD
          value: msi
        name: manager

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    azure.workload.identity/client-id: 5ad8b945-c006-4f5d-b31d-f90b6ce2bd2d
  labels:
    azure.workload.identity/use: "true"